name: Flutter Workflow
on:
  push:
    branches:
      - main

jobs:
  build_android:
    env:
      ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_ZIP_PASSPHRASE }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Get folder structure
        run: ls -lha

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Decrypt Android keys
        run: bash ./.github/scripts/decrypt_scripts.sh

      - name: Update KeyStore password in gradle properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties

      - name: Update KeyStore key password in gradle properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.6.1
        with:
          flutter-version: "3.0.5"
          channel: "stable"
      - run: flutter --version

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Build app bundle
        run: flutter build appbundle

      - name: Upload app bundle
        uses: actions/upload-artifact@v3.1.0
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  deploy_android:
    env:
      ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_ZIP_PASSPHRASE }}
    name: Deploying to playstore
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Decrypt Android keys
        run: bash ./.github/scripts/decrypt_scripts.sh

      - name: Update KeyStore password in gradle properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties

      - name: Update KeyStore key password in gradle properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.5"

      - run: flutter pub get
      - run: flutter build appbundle
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v3.1.0
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
      - name: Run fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: "production"
          subdirectory: android
